contracts/seed/SeedFactory.sol
In this PR:-
- Event at SeedFactory.SeedCreated(), now emits the address of admin.
=> Chore: New audit update fix

contracts/utils/Signer.sol, test/unit/signer.js
1) Now the SeedCreated event emits address of admin. https://github.com/PrimeDAO/contracts-v2/blob/main/contracts/seed/SeedFactory.sol#L103 
2) The Signer contract's generateSignature check for _value, _operation and _refundReceiver to be 0, CALL, address(0) respectively.
=> Chore: Added new require check for Signer.generateSignature()

hardhat.config.js
=> 71-fix-deploy-with-PK

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-chore-issue-template-.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template_for_help.md
Added templates for
- Issue/Chore
- Bug report
- PR
- PR that is opened for help from other developers
Also, I tested the **close** [*issue number*] automation in combination with extra text and it works. So we don't need to have the PR text empty.
=> Issue and PR templates

README.md, docs/contract-deployment.md, hardhat.config.js, package.json
- Added package `@nomiclabs/hardhat-etherscan`.
- Imported the package in `hardhat.config.js`
- Added a config property at `hardhat.config.js`
- Added `env` variable definition for `ETHERSCAN_API_KEY`
- Added bash command for contract verification on etherscan at `README.md`.
closes #79
=> 79 - Chore/Add hardhat-etherscan plugin for the verification of contracts.

.eslintrc.json, .prettierignore, .solcover.js, deploy/00_deploy_seed_contracts.js, deploy/01_deploy_migration_contracts.js, hardhat.config.js, package-lock.json, package.json, tasks/gnosisManagement.js, tasks/utils/gnosis.js, tasks/utils/merkle.js, test/integration/deploy-seed.js, test/test-init.js, test/unit/MerkleDrop.spec.js, test/unit/seed-factory.js, test/unit/seed.js, test/unit/signer.js
- adds `prettier` (code formatter) package
- integrates `prettier` with `eslint`
- adds command to run formatter
- uses `prettier` to format all existing JS code
closes #87
=> 87 Chore: integrate prettier

contracts/Reputation.sol
Closes https://github.com/PrimeDAO/contracts-v2/issues/99
=> 99 add comments

README.md, tasks/reputationManagement.js
=> 107 Chore: Remove verifyReputation and add readme info

contracts/migration/MerkleDrop.sol, test/unit/MerkleDrop.spec.js
=> 77-Chore: Tests for repeated merkle drops

test/unit/Reputation.spec.js
=> 119 hundred percent test coverage for reputation

deployments/rinkeby/Seed.json, exports/rinkeby.json
=> Fix: Seed ABI Rinkeby

deployments/rinkeby/SeedFactory.json, exports/rinkeby.json
=> Fix: Export correct abi for seedfactory

contracts/lbp/LBPManager.sol, contracts/lbp/LBPManagerFactory.sol, test/unit/lbp-manager-factory.js, test/unit/lbp-manager.js
- implemented all the event as outlined in the issue
- adapted tests accordingly
closes #152
=> Feature: add events

.solcover.js, contracts/lbp/LBPManager.sol, contracts/lbp/LBPManagerFactory.sol, contracts/seed/Seed.sol, contracts/seed/SeedFactory.sol, contracts/utils/CloneFactory.sol, contracts/utils/Signer.sol, contracts/utils/SignerV2.sol, contracts/utils/interface/ILBP.sol, contracts/utils/interface/ILBPFactory.sol, contracts/utils/interface/IVault.sol, contracts/utils/interface/Safe.sol, hardhat.config.js, package.json, test/unit/signer.js
Implements the following issues:-
- #185 
- #186 
- #182 
- #183 
- #194
=> Audit Chore: Fixing general problems

.solhint.json, contracts/lbp/LBPManager.sol, contracts/lbp/LBPManagerFactory.sol, contracts/utils/SignerV2.sol, test/unit/lbp-manager-factory.spec.js, test/unit/lbp-manager.spec.js, test/unit/signer-v2.spec.js
- solved all the linter warnings where possible
- silenced the ones I couldn't solve
- #187 
closes #187
=> Audit Chore: Linter emits warning

contracts/lbp/LBPManager.sol, test/unit/lbp-manager.spec.js
- Implements #217 
closes #127
=> Feature: add function getSwapEnabled

deploy/03_deploy_lbp_contracts.js
Brought the `safeInstance` out of scope.
=> Corrected deploy script

contracts/lbp/LBPManager.sol, test/unit/lbp-manager.spec.js
=> Chore: Add a require check to revert when LBP is not deployed/initialized.

contracts/lbp/LBPManager.sol
=> Chore: Resolving the most difficult issue of setting swapEnabled to false by default.

hardhat.config.js, tasks/utils/gnosis.js
=> Chore: Added RPC for Arbitrum and updated Gnosis to point to Arbitrum Safe API

.solcover.js, contracts/utils/Multicall.sol, deploy/07_deploy_multicall_contracts.js
=> Chore: Arbitrum multicall
